services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: ./API/
    ports:
      - 5000:5000
    depends_on:
      - db
  front:
    build:
      context: ./Front
    ports:
      - 4200:4200
volumes:
  postgres-data: