# base image
FROM node:16-alpine AS build

# set working directory
WORKDIR /app
# install and cache app dependencies
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli 

# add app
COPY . .

RUN npm run build

EXPOSE 4200

# start app
CMD ["ng", "serve","--host=0.0.0.0"]