services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
  postgres-data: